### ISSUE TITLE
npmjs.com package doesn't fit any tag, examples not working with package

### ISSUE THREAD

**Issue by LAV42** [metaplex/js#9]
Hello there,

I'm trying to do some first steps with the JS interface.

Using the package published to https://www.npmjs.com/package/@metaplex/js to run the examples does not work.

Since this is under heavy development I figured I should just checkout the repo at the version tagged on the npm package (0.0.1)
but turns out there are no tags.

```
$ cat package.json
{
  "dependencies": {
    "@metaplex/js": "^0.0.1"
  }
}
$ ls
index.js  index.ts  node_modules  package.json  yarn-error.log  yarn.lock
$ cat index.ts
import metaplex from "@metaplex/js";

const conn = new metaplex.Connection("mainnet-beta");
const token_mint = 'dEJhLWciCBfbBJvjJXkJeZ8nP3kGs3M2EuMQP1NXQfJ';

const { Metadata } = metaplex;
const metadata = Metadata.load(conn, token_mint);
console.log(metadata);
$ tsc index.ts
$ node index.js
[removed]/minimal_non_working/index.js:4
var conn = new js_1["default"].Connection("mainnet-beta");
                               ^

TypeError: Cannot read property 'Connection' of undefined
    at Object.<anonymous> ([removed]/minimal_non_working/index.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
$ npm -v
6.14.15
$ node -v
v14.17.6
$ yarn -v
1.22.11
$ yarn list
yarn list v1.22.11
warning package.json: No license field
warning No license field
├─ @babel/runtime@7.15.4
│  └─ regenerator-runtime@^0.13.4
├─ @metaplex/js@0.0.1
│  └─ @babel/runtime@^7.12.5
└─ regenerator-runtime@0.13.9
Done in 0.07s.
```

Thanks

**Comment by LAV42** [comment]
After spending more time in the Metaplex ecosystem I realise how early all of this is.

I suspect that my issue is going to be completely irrelevant days from now. So closing the issue for now.
